### ISSUE TITLE
Use a cadCAD task queue

### ISSUE THREAD

**Issue by sembrestels** [commons-stack/commons-simulator#1]
Our cadCAD servers will break down if multiple users try to simulate cadCAD at the same time

Use as inspiration: https://testdriven.io/blog/developing-an-asynchronous-task-queue-in-python/

**Comment by BenSchZA** [comment]
I've done some work with task queues in Python before, using Celery: see http://www.celeryproject.org/ & https://github.com/BenSchZA/wattie-whatsapp-bot

What exactly is the purpose of the task queue? Is this to queue up requests to the cadCAD model from different user sessions? 

Is the limitation of running concurrent requests with cadCAD that the server can't handle the load, or that there is a limitation with access to shared resources?

**Comment by GriffGreen** [comment]
Its an internal cadCAD problem. My understanding is that the cadCAD software itself wasn't written with parallelization in mind... I might be getting some piece of the equation wrong... but for sure that is the core problem that blockscience warned us about...

**Comment by BenSchZA** [comment]
These are some of the points that came up during brainstorming session w/ Griff & Andrew:

* caching / memoization of results (could be issue because of randomization of simulations)
* task queue (potentially with limited number of simulations in parallel?)
* the distinction between the issue of vectorization/parallel processing of cadCAD simulations vs. running simulation in separate process for each user session
* UX - countdown (store average simulation calculation time and provide this, along with queue size, to frontend)
* display previous results while you wait (considering parameters/results would be stored for scoring gamification down the line, we could potentially do this)
* user sessions (we need to handle user requests to the web server well)

I'll write up a clearer spec/scope before going ahead with this. @sembrestels let me know if you have any thoughts about the above. I think there are a few options I can try.

**Comment by Eithcowich** [comment]
If there's an issue with the simulation taking longer to generate than the players would find acceptable, maybe don't allow a range of values? I mean the value a user enters doesn't need to be continuous between a and b, it could be just a small series, like a1... a10 and that's it. (of course this depends on the number of parameters involved.) 

Then you cache all the options on the server, send json to the javascript front end, and everything flies. 

I don't have nearly enough information on cadCAD, your servers, or the game, so this is based on a totally general speculation, sorry if I put noise into the system.

**Comment by BenSchZA** [comment]
@Eithcowich that is an option, and the parameters are currently limited to a range with a slider, but there is some randomness in the simulation. So we might have to remove that randomness if we can't handle actually allowing the users to run a new simulation each time. The other issue, although maybe less of an issue compared to running a new simulation each time, is that there will be a lot of permutations for the current number of parameters, as you mention. Good suggestion and something to consider :)

**Comment by BenSchZA** [comment]
I've done a few ex[eriments, running multiple parallel requests, using `seq 1 10 | xargs -n1 -P4 curl _`. 

In more recent versions, Flask is multi-threaded by default. Matplotlib is unfortunately not thread-safe, although after a few tweaks it does actually work, with minor issues.

The first issue is that the Matplotlib figures are saved and accessed as static files on the server, which means you can't have concurrent user sessions without a file access error being thrown. To solve this I've temporarily added `threading.current_thread().ident` as a makeshift ID to create a unique plot for each request. We do need to add proper file lifecycle management in future, but for now it just proved that Flask and cadCAD can in fact handle multi-threading.

Another option, if Matplotlib not being thread-safe causes issues, is using the Python multiprocessing library, but this is limited by the server cores.

**Comment by BenSchZA** [comment]
Currently, the implementation solves the issue of the server breaking down due to multi-threading issues, but the task queue may be necessary in future for server resource issues.
