### ISSUE TITLE
Improve the final score and failure/success metrics for next release

### ISSUE THREAD

**Issue by marthendalnunes** [commons-stack/commons-simulator#102]
A suggestion for metrics:
- token price compared to hatch price
- Ratio of successful projects to failed ones is
- Overall Sentiment
- Nº of final participants compared to Nº of hatchers
- Nº/value of proposals funded
- Total spent by the funding pool compared to the amount received in the hatch phase

**Comment by GriffGreen** [comment]
My thoughts... 

**I Love:**
- token price compared to hatch price (Is this the price after 3 years?)
- Overall Sentiment (is this at the end of the 3 years?)
- Nº/value of proposals funded
- Total spent by the funding pool compared to the amount received in the hatch phase

**I also love:**
- Average amount in funding pool over time (without considering the Hatch)
- Average price compared to hatch price
- Average Sentiment over time (without considering the Hatch)

**Because they are not visible in the graphs, I don't like so much:**
Ratio of successful projects to failed ones is
Nº of final participants compared to Nº of hatchers

Although... it might be cool to have a graph that shows number of participants over time...

**Comment by marthendalnunes** [comment]
@GriffGreen Thanks for the suggestions, they make much sense. About the ratio of successful projects and Nº of final participants, I think it is pretty much done because we're thinking tho send the information of the initial/final state of all the projects to the front-end (see below) so we can show it to the user because it might be nice for the user to see how many projects got funds, failed and were a success. 

![image](https://user-images.githubusercontent.com/18421017/104125869-3822a280-5338-11eb-9392-90bbfa2c3ae2.png)

**Comment by GriffGreen** [comment]
https://docs.google.com/document/d/1GJ8Ez2qlsISz442aGZa_HkfeGQ3ZrC-MG5-F8Q0eeGg/edit

**Comment by marthendalnunes** [comment]
Unbalanced metric: 
![image](https://user-images.githubusercontent.com/18421017/106982400-d55bd580-6742-11eb-837a-a490dcb33823.png)
`calc_avg_funds_to_initial_ratio` is returning way too high values (in the image above, the max result should be ~1). We should limit the max output of each single metric.
