### ISSUE TITLE
Add more explanation to "Funding Distribution/Max Spending" Page

### ISSUE THREAD

**Issue by flakoubay** [commons-stack/commons-simulator#123]
Positive: love the design, the intro, and the art. also i was a woman organizing a meeting at akasha hub which is one of my fav place and people (nikoline).

To be improved: maybe an animated intro would be nice. some text in the intro is overlapping. throughout the process I would have liked a back button.
finally you should explain that step below a bit more (like why is it capped at 50%, and the "relative amount of spending"
<img width="1070" alt="Screen Shot 2021-01-27 at 12 33 21 PM" src="https://user-images.githubusercontent.com/59846872/106033762-10ee0400-60a0-11eb-803d-e087f673ec35.png">

thanks
F

**Comment by Danibelle** [comment]
+1 on the back button!

**Comment by GriffGreen** [comment]
@laurenluz  please address like why is it capped at 50%, and the "relative amount of spending" :-D!!

**Comment by laurenluz** [comment]
Suggestions:

1. ADD TOOL TIP @ "50%":

The maximum amount of funds that can be withdrawn at any given time is a percentage of the amount of funds that are remaining in the funding pool at that time. *click for more info

2. Edit text in "More Info":

You must select what percentage of the available funds in the Funding Pool can be distributed at any one time. This effectively sets a maximum for a single proposal (or group of proposals), ensuring that larger proposals require a greater amount of collective voting power from the community in order to pass.

The maximum amount of funds that can be withdrawn at any given time is a percentage of the amount of funds that are remaining in the funding pool at that time. This means that as funds are allocated to projects, the total amount in the pool is less, and the max amount that can be withdrawn is also less. Hence you are selecting a cap on the “relative amount of spending”. 

The maximum percentage that you are able to select as this cap is 50%. This is to limit the rate at which the funding pool can be drained.

If the threshold you select is high, it will allow large proposals to pass but may drain the funding pool too quickly. If the threshold is low, it conserves the pool but can also block essential initiatives from being approved.

@marthendalnunes can you read the above, confirm that it is true and then if so assign to @MerlinEgalite to implement in the frontend?

**Comment by laurenluz** [comment]
Hey @MerlinEgalite this text isn't updated in the simulator. Can you please fix?
